# Generated by Django 4.1.7 on 2023-04-01 01:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Telegram User'},
        ),
    ]
